name: Trigger Repo1 on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  trigger-repo1:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repo1 workflow via repository_dispatch
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.REPO2_PAT }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/rohitgxrgklt/test-repo-2/dispatches \
               -d '{"event_type": "sdk-pr-merged", "client_payload": {"pr_number": ${{ github.event.pull_request.number }}}}'
